// Centralized mock data for SELLEZY scaffold
export const LANGUAGES = [
  { code: "EN", label: "EN", name: "English" },
  { code: "HI", label: "हि", name: "हिन्दी" },
  { code: "TA", label: "தமி", name: "தமிழ்" },
  { code: "BN", label: "বাং", name: "বাংলা" },
  { code: "MR", label: "मरा", name: "मराठी" },
  { code: "HINGLISH", label: "Hinglish", name: "Hinglish" },
] as const;

export const LANG_LABELS = {
  EN: {
    greeting: "Welcome",
    logout: "Logout",
    explore: "Explore →",
    // Home page
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    producerTitle: "Producer",
    consumerTitle: "Shopper",
    homeSubline: "Here's what's happening across your product ecosystem.",
    producerToolkit: "Your Producer Toolkit",
    consumerToolkit: "Smart Shopper Toolkit",
    // Producer feature cards
    f_pipeline: "Sentiment Pipeline",
    f_pipeline_desc: "4-stage AI pipeline status and insights",
    f_reports: "Downloadable Reports",
    f_reports_desc: "Export CSV, PDF or JSON reports by category",
    f_multi: "Multilingual Overview",
    f_multi_desc: "Coverage across EN, हिन्दी, தமிழ், বাংলা, मराठी, Hinglish",
    f_health: "Product Health Scores",
    f_health_desc: "Per-product quality and defect tracking",
    f_category: "Category Comparison",
    f_category_desc: "Electronics vs FMCG vs Apparel sentiment cross-view",
    f_anomaly: "Anomaly Alerts",
    f_anomaly_desc: "Recent sentiment drops and spike detection",
    f_heatmap: "Geo Sales Heatmap",
    f_heatmap_desc: "Where products are loved most across India",
    f_community: "Community & Opportunities",
    f_community_desc: "Affiliate links, expert tips, young entrepreneur hub",
    // Consumer feature cards
    f_chatbot: "AI Assistant",
    f_chatbot_desc: "Ask anything about products, reviews, and deals",
    f_reviews: "Review Explorer",
    f_reviews_desc: "Browse smart, filtered, verified reviews",
    f_labels: "Personalized Labels",
    f_labels_desc: "Products matched to your lifestyle",
    f_trends: "Sentiment Trends",
    f_trends_desc: "See how brands improved over time",
    // Stats
    s_products: "Products Monitored",
    s_alerts: "Alerts Today",
    s_avg: "Avg. Sentiment Score",
    s_processed: "Reviews Processed",
    s_browsed: "Products Browsed",
    s_submitted: "Reviews Submitted",
    s_recs: "Recommendations",
    s_offers: "Offers Available",
    // Page titles
    pt_pipeline: "Sentiment Pipeline",
    pt_pipeline_sub: "Live status across the 4-stage AI processing pipeline.",
    pt_reports: "Downloadable Reports",
    pt_reports_sub: "Export role-specific reports in CSV, JSON or PDF.",
    pt_multi: "Multilingual Overview",
    pt_multi_sub: "Language coverage and AI translation quality.",
    pt_health: "Product Health Scores",
    pt_health_sub: "Per-product quality and defect tracking.",
    pt_category: "Category Comparison",
    pt_category_sub: "Cross-category sentiment side-by-side.",
    pt_anomaly: "Anomaly Alerts",
    pt_anomaly_sub: "Real-time sentiment anomaly detection feed.",
    pt_heatmap: "Geo Sales Heatmap",
    pt_heatmap_sub: "Where products are loved most across India.",
    pt_community: "Opportunities for Young Minds",
    pt_community_sub: "Build your edge in retail with data-driven insight.",
    pt_chatbot: "SELLEZY Assistant",
    pt_reviews: "Review Explorer",
    pt_reviews_sub: "Smart, filtered, verified reviews — across 6 languages.",
    pt_labels: "Personalized Labels",
    pt_labels_sub: "Products matched to your lifestyle profile.",
    pt_trends: "Sentiment Trends",
    pt_trends_sub: "How brands improved over time, by category.",
    // Common
    details: "Details →",
    close: "Close",
    viewMore: "View more",
    download: "Download",
    generateReport: "Generate Report",
    learnMore: "Learn more →",
    exploreResearch: "Explore Research →",
    markResolved: "Mark Resolved",
    viewPipelineStage: "View Pipeline Stage",
  },
  HI: {
    greeting: "स्वागत है",
    logout: "लॉग आउट",
    explore: "एक्सप्लोर करें →",
    goodMorning: "सुप्रभात",
    goodAfternoon: "नमस्कार",
    goodEvening: "शुभ संध्या",
    producerTitle: "निर्माता",
    consumerTitle: "खरीदार",
    homeSubline: "आपके उत्पाद इकोसिस्टम में जो हो रहा है।",
    producerToolkit: "आपका निर्माता टूलकिट",
    consumerToolkit: "स्मार्ट खरीदार टूलकिट",
    f_pipeline: "सेंटिमेंट पाइपलाइन",
    f_pipeline_desc: "4-चरण AI पाइपलाइन स्थिति और अंतर्दृष्टि",
    f_reports: "डाउनलोड योग्य रिपोर्ट",
    f_reports_desc: "श्रेणी के अनुसार CSV, PDF या JSON रिपोर्ट निर्यात करें",
    f_multi: "बहुभाषी अवलोकन",
    f_multi_desc: "EN, हिन्दी, தமிழ், বাংলা, मराठी, Hinglish में कवरेज",
    f_health: "उत्पाद स्वास्थ्य स्कोर",
    f_health_desc: "प्रति-उत्पाद गुणवत्ता और दोष ट्रैकिंग",
    f_category: "श्रेणी तुलना",
    f_category_desc: "इलेक्ट्रॉनिक्स बनाम FMCG बनाम परिधान",
    f_anomaly: "अनोमली अलर्ट",
    f_anomaly_desc: "हाल की सेंटिमेंट गिरावट और स्पाइक डिटेक्शन",
    f_heatmap: "जियो सेल्स हीटमैप",
    f_heatmap_desc: "भारत में उत्पाद कहाँ पसंद किए जाते हैं",
    f_community: "समुदाय और अवसर",
    f_community_desc: "एफिलिएट लिंक, विशेषज्ञ टिप्स, उद्यमी हब",
    f_chatbot: "AI सहायक",
    f_chatbot_desc: "उत्पादों, समीक्षाओं और सौदों के बारे में पूछें",
    f_reviews: "समीक्षा एक्सप्लोरर",
    f_reviews_desc: "स्मार्ट, फ़िल्टर्ड, सत्यापित समीक्षाएँ",
    f_labels: "वैयक्तिकृत लेबल",
    f_labels_desc: "आपकी जीवनशैली से मेल खाते उत्पाद",
    f_trends: "सेंटिमेंट ट्रेंड्स",
    f_trends_desc: "देखें ब्रांड समय के साथ कैसे बेहतर हुए",
    s_products: "मॉनिटर किए गए उत्पाद",
    s_alerts: "आज के अलर्ट",
    s_avg: "औसत सेंटिमेंट स्कोर",
    s_processed: "प्रोसेस की गई समीक्षाएँ",
    s_browsed: "ब्राउज़ किए गए उत्पाद",
    s_submitted: "सबमिट की गई समीक्षाएँ",
    s_recs: "सिफारिशें",
    s_offers: "उपलब्ध ऑफर",
    pt_pipeline: "सेंटिमेंट पाइपलाइन",
    pt_pipeline_sub: "4-चरण AI प्रोसेसिंग पाइपलाइन की लाइव स्थिति।",
    pt_reports: "डाउनलोड योग्य रिपोर्ट",
    pt_reports_sub: "CSV, JSON या PDF में भूमिका-विशिष्ट रिपोर्ट निर्यात करें।",
    pt_multi: "बहुभाषी अवलोकन",
    pt_multi_sub: "भाषा कवरेज और AI अनुवाद गुणवत्ता।",
    pt_health: "उत्पाद स्वास्थ्य स्कोर",
    pt_health_sub: "प्रति-उत्पाद गुणवत्ता और दोष ट्रैकिंग।",
    pt_category: "श्रेणी तुलना",
    pt_category_sub: "क्रॉस-श्रेणी सेंटिमेंट साथ-साथ।",
    pt_anomaly: "अनोमली अलर्ट",
    pt_anomaly_sub: "रीयल-टाइम सेंटिमेंट अनोमली डिटेक्शन फ़ीड।",
    pt_heatmap: "जियो सेल्स हीटमैप",
    pt_heatmap_sub: "भारत में उत्पाद कहाँ पसंद किए जाते हैं।",
    pt_community: "युवाओं के लिए अवसर",
    pt_community_sub: "डेटा-संचालित अंतर्दृष्टि के साथ अपनी बढ़त बनाएँ।",
    pt_chatbot: "SELLEZY सहायक",
    pt_reviews: "समीक्षा एक्सप्लोरर",
    pt_reviews_sub: "स्मार्ट, फ़िल्टर्ड, सत्यापित समीक्षाएँ — 6 भाषाओं में।",
    pt_labels: "वैयक्तिकृत लेबल",
    pt_labels_sub: "आपकी जीवनशैली प्रोफ़ाइल से मेल खाते उत्पाद।",
    pt_trends: "सेंटिमेंट ट्रेंड्स",
    pt_trends_sub: "श्रेणी के अनुसार समय के साथ ब्रांड कैसे सुधरे।",
    details: "विवरण →",
    close: "बंद करें",
    viewMore: "और देखें",
    download: "डाउनलोड",
    generateReport: "रिपोर्ट बनाएँ",
    learnMore: "और जानें →",
    exploreResearch: "शोध देखें →",
    markResolved: "हल किया गया",
    viewPipelineStage: "पाइपलाइन चरण देखें",
  },
  TA: {
    greeting: "வரவேற்கிறோம்",
    logout: "வெளியேறு",
    explore: "ஆராயுங்கள் →",
    goodMorning: "காலை வணக்கம்",
    goodAfternoon: "மதிய வணக்கம்",
    goodEvening: "மாலை வணக்கம்",
    producerTitle: "உற்பத்தியாளர்",
    consumerTitle: "வாங்குபவர்",
    homeSubline: "உங்கள் தயாரிப்பு சூழலில் என்ன நடக்கிறது.",
    producerToolkit: "உங்கள் உற்பத்தியாளர் கருவிகள்",
    consumerToolkit: "ஸ்மார்ட் வாங்குபவர் கருவிகள்",
    f_pipeline: "சென்டிமென்ட் பைப்லைன்",
    f_pipeline_desc: "4-நிலை AI பைப்லைன் நிலை மற்றும் நுண்ணறிவு",
    f_reports: "பதிவிறக்க அறிக்கைகள்",
    f_reports_desc: "வகை வாரியாக CSV, PDF அல்லது JSON அறிக்கைகள்",
    f_multi: "பல மொழி கண்ணோட்டம்",
    f_multi_desc: "EN, हिन्दी, தமிழ், বাংলা, मराठी, Hinglish கவரேஜ்",
    f_health: "தயாரிப்பு ஆரோக்கிய மதிப்பெண்கள்",
    f_health_desc: "ஒவ்வொரு தயாரிப்பு தர மற்றும் குறைபாடு கண்காணிப்பு",
    f_category: "வகை ஒப்பீடு",
    f_category_desc: "எலக்ட்ரானிக்ஸ் vs FMCG vs ஆடை",
    f_anomaly: "அசாதாரண எச்சரிக்கைகள்",
    f_anomaly_desc: "சமீபத்திய சென்டிமென்ட் வீழ்ச்சிகள்",
    f_heatmap: "புவியியல் விற்பனை வெப்ப வரைபடம்",
    f_heatmap_desc: "இந்தியா முழுவதும் தயாரிப்புகள் எங்கே விரும்பப்படுகின்றன",
    f_community: "சமூகம் & வாய்ப்புகள்",
    f_community_desc: "அஃபிலியேட், நிபுணர் குறிப்புகள், தொழில்முனைவோர் மையம்",
    f_chatbot: "AI உதவியாளர்",
    f_chatbot_desc: "தயாரிப்புகள், மதிப்புரைகள், சலுகைகள் பற்றி கேளுங்கள்",
    f_reviews: "மதிப்புரை எக்ஸ்ப்ளோரர்",
    f_reviews_desc: "ஸ்மார்ட், வடிகட்டப்பட்ட, சரிபார்க்கப்பட்ட மதிப்புரைகள்",
    f_labels: "தனிப்பயனாக்கப்பட்ட லேபிள்கள்",
    f_labels_desc: "உங்கள் வாழ்க்கை முறைக்கு பொருந்தும் தயாரிப்புகள்",
    f_trends: "சென்டிமென்ட் போக்குகள்",
    f_trends_desc: "காலப்போக்கில் பிராண்டுகள் எப்படி மேம்பட்டன",
    s_products: "கண்காணிக்கப்பட்ட தயாரிப்புகள்",
    s_alerts: "இன்றைய எச்சரிக்கைகள்",
    s_avg: "சராசரி சென்டிமென்ட் மதிப்பெண்",
    s_processed: "செயலாக்கப்பட்ட மதிப்புரைகள்",
    s_browsed: "உலாவப்பட்ட தயாரிப்புகள்",
    s_submitted: "சமர்ப்பிக்கப்பட்ட மதிப்புரைகள்",
    s_recs: "பரிந்துரைகள்",
    s_offers: "சலுகைகள்",
    pt_pipeline: "சென்டிமென்ட் பைப்லைன்",
    pt_pipeline_sub: "4-நிலை AI செயலாக்க பைப்லைன் நேரடி நிலை.",
    pt_reports: "பதிவிறக்க அறிக்கைகள்",
    pt_reports_sub: "CSV, JSON அல்லது PDF இல் அறிக்கைகளை ஏற்றுமதி செய்யுங்கள்.",
    pt_multi: "பல மொழி கண்ணோட்டம்",
    pt_multi_sub: "மொழி கவரேஜ் மற்றும் AI மொழிபெயர்ப்பு தரம்.",
    pt_health: "தயாரிப்பு ஆரோக்கிய மதிப்பெண்கள்",
    pt_health_sub: "ஒவ்வொரு தயாரிப்பு தர மற்றும் குறைபாடு கண்காணிப்பு.",
    pt_category: "வகை ஒப்பீடு",
    pt_category_sub: "வகை-வாரியான சென்டிமென்ட் ஒப்பீடு.",
    pt_anomaly: "அசாதாரண எச்சரிக்கைகள்",
    pt_anomaly_sub: "நேரடி சென்டிமென்ட் அசாதாரண கண்டறிதல் ஃபீட்.",
    pt_heatmap: "புவியியல் விற்பனை வெப்ப வரைபடம்",
    pt_heatmap_sub: "இந்தியா முழுவதும் தயாரிப்புகள் எங்கே விரும்பப்படுகின்றன.",
    pt_community: "இளைஞர்களுக்கான வாய்ப்புகள்",
    pt_community_sub: "தரவு சார்ந்த நுண்ணறிவுடன் உங்கள் முன்னுரிமையை உருவாக்கவும்.",
    pt_chatbot: "SELLEZY உதவியாளர்",
    pt_reviews: "மதிப்புரை எக்ஸ்ப்ளோரர்",
    pt_reviews_sub: "6 மொழிகளில் ஸ்மார்ட், வடிகட்டப்பட்ட மதிப்புரைகள்.",
    pt_labels: "தனிப்பயனாக்கப்பட்ட லேபிள்கள்",
    pt_labels_sub: "உங்கள் வாழ்க்கை முறை சுயவிவரத்திற்கு பொருந்தும் தயாரிப்புகள்.",
    pt_trends: "சென்டிமென்ட் போக்குகள்",
    pt_trends_sub: "வகை வாரியாக காலப்போக்கில் பிராண்டுகள் எப்படி மேம்பட்டன.",
    details: "விவரங்கள் →",
    close: "மூடு",
    viewMore: "மேலும் காண்க",
    download: "பதிவிறக்க",
    generateReport: "அறிக்கை உருவாக்கு",
    learnMore: "மேலும் அறிய →",
    exploreResearch: "ஆராய்ச்சியைக் காண்க →",
    markResolved: "தீர்க்கப்பட்டது",
    viewPipelineStage: "பைப்லைன் நிலையைக் காண்க",
  },
  BN: {
    greeting: "স্বাগতম",
    logout: "লগ আউট",
    explore: "অন্বেষণ করুন →",
    goodMorning: "শুভ সকাল",
    goodAfternoon: "শুভ অপরাহ্ন",
    goodEvening: "শুভ সন্ধ্যা",
    producerTitle: "প্রস্তুতকারক",
    consumerTitle: "ক্রেতা",
    homeSubline: "আপনার পণ্য ইকোসিস্টেমে যা ঘটছে।",
    producerToolkit: "আপনার প্রস্তুতকারক টুলকিট",
    consumerToolkit: "স্মার্ট ক্রেতা টুলকিট",
    f_pipeline: "সেন্টিমেন্ট পাইপলাইন",
    f_pipeline_desc: "4-পর্যায়ের AI পাইপলাইন স্ট্যাটাস",
    f_reports: "ডাউনলোডযোগ্য রিপোর্ট",
    f_reports_desc: "বিভাগ অনুসারে CSV, PDF বা JSON রিপোর্ট",
    f_multi: "বহুভাষিক ওভারভিউ",
    f_multi_desc: "EN, हिन्दी, தமிழ், বাংলা, मराठी, Hinglish কভারেজ",
    f_health: "পণ্য স্বাস্থ্য স্কোর",
    f_health_desc: "প্রতি-পণ্য মান এবং ত্রুটি ট্র্যাকিং",
    f_category: "বিভাগ তুলনা",
    f_category_desc: "ইলেকট্রনিক্স বনাম FMCG বনাম পোশাক",
    f_anomaly: "অস্বাভাবিকতা সতর্কতা",
    f_anomaly_desc: "সাম্প্রতিক সেন্টিমেন্ট পতন",
    f_heatmap: "ভৌগলিক বিক্রয় হিটম্যাপ",
    f_heatmap_desc: "ভারত জুড়ে পণ্য কোথায় পছন্দ হয়",
    f_community: "সম্প্রদায় ও সুযোগ",
    f_community_desc: "অ্যাফিলিয়েট, বিশেষজ্ঞ টিপস, উদ্যোক্তা হাব",
    f_chatbot: "AI সহকারী",
    f_chatbot_desc: "পণ্য, রিভিউ এবং ডিল সম্পর্কে জিজ্ঞাসা করুন",
    f_reviews: "রিভিউ এক্সপ্লোরার",
    f_reviews_desc: "স্মার্ট, ফিল্টার্ড, যাচাইকৃত রিভিউ",
    f_labels: "ব্যক্তিগতকৃত লেবেল",
    f_labels_desc: "আপনার জীবনধারার সাথে মানানসই পণ্য",
    f_trends: "সেন্টিমেন্ট ট্রেন্ড",
    f_trends_desc: "ব্র্যান্ডগুলি সময়ের সাথে কীভাবে উন্নত হয়েছে",
    s_products: "মনিটর করা পণ্য",
    s_alerts: "আজকের সতর্কতা",
    s_avg: "গড় সেন্টিমেন্ট স্কোর",
    s_processed: "প্রক্রিয়াকৃত রিভিউ",
    s_browsed: "ব্রাউজ করা পণ্য",
    s_submitted: "জমা দেওয়া রিভিউ",
    s_recs: "সুপারিশ",
    s_offers: "অফার",
    pt_pipeline: "সেন্টিমেন্ট পাইপলাইন",
    pt_pipeline_sub: "4-পর্যায়ের AI প্রক্রিয়াকরণ পাইপলাইনের লাইভ স্ট্যাটাস।",
    pt_reports: "ডাউনলোডযোগ্য রিপোর্ট",
    pt_reports_sub: "CSV, JSON বা PDF এ রিপোর্ট রপ্তানি করুন।",
    pt_multi: "বহুভাষিক ওভারভিউ",
    pt_multi_sub: "ভাষা কভারেজ এবং AI অনুবাদ মান।",
    pt_health: "পণ্য স্বাস্থ্য স্কোর",
    pt_health_sub: "প্রতি-পণ্য মান এবং ত্রুটি ট্র্যাকিং।",
    pt_category: "বিভাগ তুলনা",
    pt_category_sub: "ক্রস-বিভাগ সেন্টিমেন্ট পাশাপাশি।",
    pt_anomaly: "অস্বাভাবিকতা সতর্কতা",
    pt_anomaly_sub: "রিয়েল-টাইম সেন্টিমেন্ট অস্বাভাবিকতা ফিড।",
    pt_heatmap: "ভৌগলিক বিক্রয় হিটম্যাপ",
    pt_heatmap_sub: "ভারত জুড়ে পণ্য কোথায় পছন্দ হয়।",
    pt_community: "তরুণদের জন্য সুযোগ",
    pt_community_sub: "ডেটা-চালিত অন্তর্দৃষ্টি দিয়ে এগিয়ে যান।",
    pt_chatbot: "SELLEZY সহকারী",
    pt_reviews: "রিভিউ এক্সপ্লোরার",
    pt_reviews_sub: "6 ভাষায় স্মার্ট, ফিল্টার্ড রিভিউ।",
    pt_labels: "ব্যক্তিগতকৃত লেবেল",
    pt_labels_sub: "আপনার জীবনধারা প্রোফাইলের সাথে মানানসই পণ্য।",
    pt_trends: "সেন্টিমেন্ট ট্রেন্ড",
    pt_trends_sub: "বিভাগ অনুসারে সময়ের সাথে ব্র্যান্ড উন্নতি।",
    details: "বিস্তারিত →",
    close: "বন্ধ",
    viewMore: "আরও দেখুন",
    download: "ডাউনলোড",
    generateReport: "রিপোর্ট তৈরি করুন",
    learnMore: "আরও জানুন →",
    exploreResearch: "গবেষণা দেখুন →",
    markResolved: "সমাধান হয়েছে",
    viewPipelineStage: "পাইপলাইন পর্যায় দেখুন",
  },
  MR: {
    greeting: "स्वागत आहे",
    logout: "लॉग आउट",
    explore: "एक्सप्लोर करा →",
    goodMorning: "सुप्रभात",
    goodAfternoon: "नमस्कार",
    goodEvening: "शुभ संध्याकाळ",
    producerTitle: "उत्पादक",
    consumerTitle: "खरेदीदार",
    homeSubline: "तुमच्या उत्पादन इकोसिस्टममध्ये काय चालले आहे.",
    producerToolkit: "तुमचा उत्पादक टूलकिट",
    consumerToolkit: "स्मार्ट खरेदीदार टूलकिट",
    f_pipeline: "सेंटिमेंट पाइपलाइन",
    f_pipeline_desc: "4-टप्प्यांची AI पाइपलाइन स्थिती",
    f_reports: "डाउनलोड करण्यायोग्य अहवाल",
    f_reports_desc: "श्रेणीनुसार CSV, PDF किंवा JSON अहवाल",
    f_multi: "बहुभाषिक विहंगावलोकन",
    f_multi_desc: "EN, हिन्दी, தமிழ், বাংলা, मराठी, Hinglish कव्हरेज",
    f_health: "उत्पाद आरोग्य स्कोअर",
    f_health_desc: "प्रति-उत्पाद गुणवत्ता आणि दोष ट्रॅकिंग",
    f_category: "श्रेणी तुलना",
    f_category_desc: "इलेक्ट्रॉनिक्स विरुद्ध FMCG विरुद्ध परिधान",
    f_anomaly: "अनोमली अलर्ट",
    f_anomaly_desc: "अलीकडील सेंटिमेंट घसरण",
    f_heatmap: "जिओ सेल्स हीटमॅप",
    f_heatmap_desc: "भारतात उत्पादने कुठे आवडतात",
    f_community: "समुदाय आणि संधी",
    f_community_desc: "अॅफिलिएट, तज्ञ टिप्स, उद्योजक हब",
    f_chatbot: "AI सहाय्यक",
    f_chatbot_desc: "उत्पादने, पुनरावलोकने आणि डील्सबद्दल विचारा",
    f_reviews: "पुनरावलोकन एक्सप्लोरर",
    f_reviews_desc: "स्मार्ट, फिल्टर केलेले, सत्यापित पुनरावलोकने",
    f_labels: "वैयक्तिकृत लेबल्स",
    f_labels_desc: "तुमच्या जीवनशैलीशी जुळणारी उत्पादने",
    f_trends: "सेंटिमेंट ट्रेंड्स",
    f_trends_desc: "ब्रँड्स कालांतराने कसे सुधारले",
    s_products: "मॉनिटर केलेली उत्पादने",
    s_alerts: "आजचे अलर्ट",
    s_avg: "सरासरी सेंटिमेंट स्कोअर",
    s_processed: "प्रक्रिया केलेली पुनरावलोकने",
    s_browsed: "ब्राउझ केलेली उत्पादने",
    s_submitted: "सबमिट केलेली पुनरावलोकने",
    s_recs: "शिफारसी",
    s_offers: "ऑफर्स",
    pt_pipeline: "सेंटिमेंट पाइपलाइन",
    pt_pipeline_sub: "4-टप्प्यांच्या AI पाइपलाइनची लाइव्ह स्थिती.",
    pt_reports: "डाउनलोड अहवाल",
    pt_reports_sub: "CSV, JSON किंवा PDF मध्ये अहवाल निर्यात करा.",
    pt_multi: "बहुभाषिक विहंगावलोकन",
    pt_multi_sub: "भाषा कव्हरेज आणि AI भाषांतर गुणवत्ता.",
    pt_health: "उत्पाद आरोग्य स्कोअर",
    pt_health_sub: "प्रति-उत्पाद गुणवत्ता ट्रॅकिंग.",
    pt_category: "श्रेणी तुलना",
    pt_category_sub: "क्रॉस-श्रेणी सेंटिमेंट तुलना.",
    pt_anomaly: "अनोमली अलर्ट",
    pt_anomaly_sub: "रिअल-टाइम सेंटिमेंट अनोमली फीड.",
    pt_heatmap: "जिओ सेल्स हीटमॅप",
    pt_heatmap_sub: "भारतात उत्पादने कुठे आवडतात.",
    pt_community: "तरुण मनांसाठी संधी",
    pt_community_sub: "डेटा-चालित अंतर्दृष्टीसह आपली धार तयार करा.",
    pt_chatbot: "SELLEZY सहाय्यक",
    pt_reviews: "पुनरावलोकन एक्सप्लोरर",
    pt_reviews_sub: "6 भाषांमध्ये स्मार्ट पुनरावलोकने.",
    pt_labels: "वैयक्तिकृत लेबल्स",
    pt_labels_sub: "तुमच्या जीवनशैलीशी जुळणारी उत्पादने.",
    pt_trends: "सेंटिमेंट ट्रेंड्स",
    pt_trends_sub: "श्रेणीनुसार कालांतराने ब्रँड सुधारणा.",
    details: "तपशील →",
    close: "बंद करा",
    viewMore: "अधिक पहा",
    download: "डाउनलोड",
    generateReport: "अहवाल तयार करा",
    learnMore: "अधिक जाणून घ्या →",
    exploreResearch: "संशोधन पहा →",
    markResolved: "निराकरण झाले",
    viewPipelineStage: "पाइपलाइन टप्पा पहा",
  },
  HINGLISH: {
    greeting: "Welcome yaar",
    logout: "Logout karo",
    explore: "Dekho →",
    goodMorning: "Good morning bhai",
    goodAfternoon: "Good afternoon bhai",
    goodEvening: "Good evening bhai",
    producerTitle: "Producer",
    consumerTitle: "Shopper",
    homeSubline: "Tumhare product ecosystem mein kya ho raha hai.",
    producerToolkit: "Tumhara Producer Toolkit",
    consumerToolkit: "Smart Shopper Toolkit",
    f_pipeline: "Sentiment Pipeline",
    f_pipeline_desc: "4-stage AI pipeline ka status aur insights",
    f_reports: "Downloadable Reports",
    f_reports_desc: "Category wise CSV, PDF ya JSON reports",
    f_multi: "Multilingual Overview",
    f_multi_desc: "6 bhashaon mein coverage",
    f_health: "Product Health Scores",
    f_health_desc: "Per-product quality aur defect tracking",
    f_category: "Category Comparison",
    f_category_desc: "Electronics vs FMCG vs Apparel",
    f_anomaly: "Anomaly Alerts",
    f_anomaly_desc: "Sentiment drops aur spikes",
    f_heatmap: "Geo Sales Heatmap",
    f_heatmap_desc: "Bharat mein products kahan pasand kiye jaate hain",
    f_community: "Community & Opportunities",
    f_community_desc: "Affiliate, expert tips, entrepreneur hub",
    f_chatbot: "AI Assistant",
    f_chatbot_desc: "Products, reviews aur deals ke baare mein puchho",
    f_reviews: "Review Explorer",
    f_reviews_desc: "Smart, filtered, verified reviews",
    f_labels: "Personalized Labels",
    f_labels_desc: "Tumhari lifestyle ke hisaab se products",
    f_trends: "Sentiment Trends",
    f_trends_desc: "Dekho brands time ke saath kaise improve hue",
    s_products: "Products Monitored",
    s_alerts: "Aaj ke Alerts",
    s_avg: "Avg Sentiment Score",
    s_processed: "Reviews Processed",
    s_browsed: "Products Dekhe",
    s_submitted: "Reviews Submit kiye",
    s_recs: "Recommendations",
    s_offers: "Offers",
    pt_pipeline: "Sentiment Pipeline",
    pt_pipeline_sub: "4-stage AI pipeline ka live status.",
    pt_reports: "Downloadable Reports",
    pt_reports_sub: "CSV, JSON ya PDF mein reports export karo.",
    pt_multi: "Multilingual Overview",
    pt_multi_sub: "Language coverage aur AI translation quality.",
    pt_health: "Product Health Scores",
    pt_health_sub: "Per-product quality aur defect tracking.",
    pt_category: "Category Comparison",
    pt_category_sub: "Cross-category sentiment side-by-side.",
    pt_anomaly: "Anomaly Alerts",
    pt_anomaly_sub: "Real-time sentiment anomaly feed.",
    pt_heatmap: "Geo Sales Heatmap",
    pt_heatmap_sub: "Bharat mein products kahan pasand hain.",
    pt_community: "Young Minds ke liye Opportunities",
    pt_community_sub: "Data-driven insight se aage badho.",
    pt_chatbot: "SELLEZY Assistant",
    pt_reviews: "Review Explorer",
    pt_reviews_sub: "6 bhashaon mein smart, verified reviews.",
    pt_labels: "Personalized Labels",
    pt_labels_sub: "Tumhari lifestyle profile ke hisaab se products.",
    pt_trends: "Sentiment Trends",
    pt_trends_sub: "Category wise time ke saath brand improvement.",
    details: "Details →",
    close: "Band karo",
    viewMore: "Aur dekho",
    download: "Download",
    generateReport: "Report banao",
    learnMore: "Aur jaano →",
    exploreResearch: "Research dekho →",
    markResolved: "Resolved",
    viewPipelineStage: "Pipeline Stage dekho",
  },
} as const;

export const CATEGORY_MINI = [
  { name: "P1", v: 60 }, { name: "P2", v: 80 }, { name: "P3", v: 45 },
];

export const PIPELINE_LANG_BREAKDOWN = [
  { name: "EN", value: 45, fill: "hsl(174 62% 47%)" },
  { name: "हिन्दी", value: 22, fill: "hsl(169 100% 55%)" },
  { name: "தமிழ்", value: 13, fill: "hsl(195 70% 60%)" },
  { name: "বাংলা", value: 10, fill: "hsl(210 60% 55%)" },
  { name: "मराठी", value: 6, fill: "hsl(27 87% 67%)" },
  { name: "Hinglish", value: 4, fill: "hsl(280 50% 60%)" },
];

export const SENTIMENT_FEATURE_DATA: Record<string, Array<{ feature: string; positive: number; neutral: number; negative: number }>> = {
  Electronics: [
    { feature: "Packaging", positive: 72, neutral: 18, negative: 10 },
    { feature: "Delivery", positive: 80, neutral: 12, negative: 8 },
    { feature: "Quality", positive: 78, neutral: 15, negative: 7 },
    { feature: "Durability", positive: 70, neutral: 20, negative: 10 },
    { feature: "Support", positive: 65, neutral: 22, negative: 13 },
    { feature: "Value", positive: 74, neutral: 17, negative: 9 },
  ],
  FMCG: [
    { feature: "Packaging", positive: 58, neutral: 24, negative: 18 },
    { feature: "Delivery", positive: 79, neutral: 14, negative: 7 },
    { feature: "Quality", positive: 82, neutral: 12, negative: 6 },
    { feature: "Durability", positive: 68, neutral: 22, negative: 10 },
    { feature: "Support", positive: 70, neutral: 20, negative: 10 },
    { feature: "Value", positive: 85, neutral: 10, negative: 5 },
  ],
  Apparel: [
    { feature: "Packaging", positive: 76, neutral: 16, negative: 8 },
    { feature: "Delivery", positive: 73, neutral: 17, negative: 10 },
    { feature: "Quality", positive: 76, neutral: 16, negative: 8 },
    { feature: "Durability", positive: 76, neutral: 18, negative: 6 },
    { feature: "Support", positive: 68, neutral: 22, negative: 10 },
    { feature: "Value", positive: 80, neutral: 14, negative: 6 },
  ],
};

export const QUALITY_TIMESERIES = Array.from({ length: 12 }, (_, i) => ({
  week: `W${i + 1}`,
  Electronics: 70 + Math.round(Math.sin(i / 2) * 6) + (i === 7 ? -8 : 0),
  FMCG: 75 + Math.round(Math.cos(i / 3) * 5) + (i === 4 ? -10 : 0),
  Apparel: 72 + Math.round(Math.sin(i / 4) * 4),
}));

export const STATE_INTENSITY: Record<string, number> = {
  Karnataka: 842, Maharashtra: 1204, "Tamil Nadu": 987, Delhi: 1456,
  "West Bengal": 623, Gujarat: 712, Rajasthan: 488, "Uttar Pradesh": 1102,
  Kerala: 540, Telangana: 690, Punjab: 410, Haryana: 520, "Madhya Pradesh": 480,
  Bihar: 340, Odisha: 290, Assam: 220, Jharkhand: 210, Chhattisgarh: 180,
  Uttarakhand: 160, "Himachal Pradesh": 130, Goa: 95, Tripura: 70, Manipur: 55,
  Meghalaya: 50, Nagaland: 40, Mizoram: 35, "Arunachal Pradesh": 30, Sikkim: 25,
  "Jammu and Kashmir": 180, "Andhra Pradesh": 760,
};

export const COMMUNITY_POSTS = [
  { id: 1, name: "Riya M.", city: "Bengaluru", initials: "RM", color: "from-pink-500 to-rose-400", text: "Found this Boat earphones deal — 91% positive reviews on durability. Check it out!", category: "Electronics", affiliate: true, lang: "EN", seedComments: [
    { user: "Aman P.", initials: "AP", text: "Just ordered, thanks for the heads up!" },
    { user: "Neha T.", initials: "NT", text: "Battery life is unreal. Worth every rupee." },
    { user: "Karan B.", initials: "KB", text: "Got mine last week — bass is solid." },
  ] },
  { id: 2, name: "Arjun K.", city: "Chennai", initials: "AK", color: "from-amber-500 to-orange-400", text: "MTR Foods packaging improved a lot this quarter based on recent reviews!", original: "MTR உணவு பேக்கேஜிங் இந்த காலாண்டில் மிகவும் மேம்பட்டது!", category: "FMCG", affiliate: false, lang: "TA", seedComments: [
    { user: "Sundar V.", initials: "SV", text: "Confirmed, no leaks anymore." },
    { user: "Lakshmi R.", initials: "LR", text: "Big improvement, finally!" },
    { user: "Vikram S.", initials: "VS", text: "Hope they keep it consistent." },
  ] },
  { id: 3, name: "Priya S.", city: "Mumbai", initials: "PS", color: "from-teal-500 to-cyan-400", text: "Running a small D2C brand? SELLEZY showed me my negative review clusters — fixed packaging in 2 weeks!", category: "Apparel", affiliate: false, lang: "EN", seedComments: [
    { user: "Tanvi M.", initials: "TM", text: "How did you set up the alerts?" },
    { user: "Rahul J.", initials: "RJ", text: "Inspirational! Doing this next." },
    { user: "Anita G.", initials: "AG", text: "Where do I start as a tiny brand?" },
  ] },
  { id: 4, name: "Rohit D.", city: "Delhi", initials: "RD", color: "from-indigo-500 to-blue-400", text: "Which is the best budget smartphone right now? Let me know in comments!", category: "Electronics", affiliate: false, lang: "EN", seedComments: [
    { user: "Sneha L.", initials: "SL", text: "Realme Narzo for sure." },
    { user: "Kabir N.", initials: "KN", text: "Try Moto G54, very underrated." },
    { user: "Pooja H.", initials: "PH", text: "Samsung A14 served me well." },
  ] },
  { id: 5, name: "Deepa N.", city: "Kolkata", initials: "DN", color: "from-purple-500 to-fuchsia-400", text: "Apparel quality scores are rising — good time for small sellers to enter the market.", original: "পোশাকের মানের স্কোর বাড়ছে — ছোট বিক্রেতাদের বাজারে প্রবেশের ভাল সময়।", category: "Apparel", affiliate: false, lang: "BN", seedComments: [
    { user: "Aditi C.", initials: "AC", text: "Agreed, our brand sentiment jumped 12 pts." },
    { user: "Rishi M.", initials: "RM", text: "Looking at fabric upgrades myself." },
    { user: "Joy B.", initials: "JB", text: "Where do you get your data from?" },
  ] },
];

export const AFFILIATE_PRODUCTS = [
  { name: "Boat Airdopes 141", category: "Electronics", score: 91, persona: "Best for Students", store: "Amazon" },
  { name: "Amul Pure Ghee 1L", category: "FMCG", score: 94, persona: "Good for Family Use", store: "Flipkart" },
  { name: "Allen Solly Polo Tee", category: "Apparel", score: 86, persona: "Best for Office", store: "Amazon" },
  { name: "Mi Smart Band 7", category: "Electronics", score: 83, persona: "Heavy Users Only", store: "Flipkart" },
  { name: "Tata Sampann Dal", category: "FMCG", score: 88, persona: "Good for Family Use", store: "Amazon" },
];

// ===== NEW DATA FOR v1.1 PAGES =====

export const PRODUCT_HEALTH: Record<string, Array<{ name: string; score: number; quality: number; durability: number; packaging: number; delivery: number; trend: "up" | "down" | "flat" }>> = {
  Electronics: [
    { name: "iPhone 15", score: 88, quality: 90, durability: 88, packaging: 84, delivery: 90, trend: "up" },
    { name: "Samsung Galaxy A54", score: 74, quality: 75, durability: 72, packaging: 78, delivery: 70, trend: "flat" },
    { name: "boAt Airdopes 141", score: 91, quality: 92, durability: 90, packaging: 88, delivery: 94, trend: "up" },
    { name: "Realme Narzo 60", score: 62, quality: 65, durability: 58, packaging: 62, delivery: 64, trend: "down" },
    { name: "Noise ColorFit Pro 4", score: 79, quality: 80, durability: 78, packaging: 76, delivery: 82, trend: "up" },
    { name: "Mi Smart Band 8", score: 83, quality: 85, durability: 82, packaging: 80, delivery: 86, trend: "flat" },
    { name: "OnePlus Nord CE3", score: 71, quality: 73, durability: 70, packaging: 68, delivery: 73, trend: "down" },
    { name: "JBL Tune 230NC", score: 85, quality: 86, durability: 84, packaging: 82, delivery: 88, trend: "up" },
  ],
  FMCG: [
    { name: "Amul Pure Ghee", score: 94, quality: 95, durability: 92, packaging: 90, delivery: 96, trend: "up" },
    { name: "Tata Sampann Dal", score: 88, quality: 90, durability: 86, packaging: 84, delivery: 92, trend: "up" },
    { name: "MTR Foods Mix", score: 85, quality: 88, durability: 82, packaging: 80, delivery: 90, trend: "up" },
    { name: "Britannia Cookies", score: 76, quality: 78, durability: 74, packaging: 70, delivery: 82, trend: "flat" },
    { name: "Maggi Noodles", score: 82, quality: 84, durability: 80, packaging: 78, delivery: 86, trend: "flat" },
    { name: "Parle-G Biscuits", score: 87, quality: 88, durability: 86, packaging: 84, delivery: 90, trend: "up" },
    { name: "Saffola Oil", score: 79, quality: 82, durability: 76, packaging: 74, delivery: 84, trend: "down" },
    { name: "Haldiram's Snacks", score: 80, quality: 82, durability: 78, packaging: 76, delivery: 84, trend: "flat" },
  ],
  Apparel: [
    { name: "Allen Solly Polo", score: 86, quality: 88, durability: 84, packaging: 82, delivery: 90, trend: "up" },
    { name: "FabIndia Kurta", score: 82, quality: 86, durability: 80, packaging: 78, delivery: 84, trend: "up" },
    { name: "Levi's 511 Jeans", score: 89, quality: 90, durability: 92, packaging: 84, delivery: 90, trend: "up" },
    { name: "Biba Suit Set", score: 75, quality: 78, durability: 72, packaging: 74, delivery: 76, trend: "flat" },
    { name: "Puma Sports Tee", score: 78, quality: 80, durability: 76, packaging: 74, delivery: 82, trend: "flat" },
    { name: "Manyavar Sherwani", score: 84, quality: 88, durability: 80, packaging: 84, delivery: 84, trend: "up" },
    { name: "W Indian Wear", score: 71, quality: 74, durability: 68, packaging: 70, delivery: 72, trend: "down" },
    { name: "Adidas Track Pant", score: 80, quality: 82, durability: 78, packaging: 76, delivery: 84, trend: "flat" },
  ],
};

export const RADAR_CATEGORY_COMPARE = [
  { axis: "Quality", Electronics: 78, FMCG: 91, Apparel: 76 },
  { axis: "Delivery", Electronics: 87, FMCG: 79, Apparel: 73 },
  { axis: "Packaging", Electronics: 72, FMCG: 62, Apparel: 76 },
  { axis: "Durability", Electronics: 70, FMCG: 68, Apparel: 61 },
  { axis: "Value", Electronics: 74, FMCG: 85, Apparel: 84 },
  { axis: "Support", Electronics: 58, FMCG: 70, Apparel: 68 },
];

export const ANOMALY_ALERTS = [
  { id: 1, severity: "critical", title: "FMCG Packaging Defect Spike", desc: "Packaging complaints spiked.", category: "FMCG", region: "Maharashtra", batch: "Batch #A204", change: "Packaging sentiment: 71% → 48% (↓23 pts in 48h)", time: "12 min ago", resolved: false },
  { id: 2, severity: "warning", title: "Electronics Delivery SLA Drop", desc: "Last-mile delivery declining.", category: "Electronics", region: "Tamil Nadu", batch: "SKU group", change: "Delivery: 84% → 67% (↓17 pts in 4 weeks)", time: "1 hr ago", resolved: false },
  { id: 3, severity: "critical", title: "FMCG Taste Complaints", desc: "Recipe change suspected.", category: "FMCG", region: "West Bengal", batch: "Batch #B112", change: "Taste: 78% → 47% (↓31 pts)", time: "3 hr ago", resolved: false },
  { id: 4, severity: "warning", title: "Apparel Durability Concerns", desc: "Color fade after wash.", category: "Apparel", region: "Delhi", batch: "Batch #C031", change: "Durability: 76% → 64% (↓12 pts)", time: "5 hr ago", resolved: false },
  { id: 5, severity: "resolved", title: "Electronics Battery Recovery", desc: "Sentiment recovered after firmware fix.", category: "Electronics", region: "Pan-India", batch: "All", change: "Battery: 74% → 82% (+8 pts)", time: "Yesterday", resolved: true },
  { id: 6, severity: "warning", title: "FMCG Quality Slip", desc: "Minor quality dip detected.", category: "FMCG", region: "Karnataka", batch: "Batch #A301", change: "Quality: 88% → 79% (↓9 pts)", time: "Yesterday", resolved: false },
  { id: 7, severity: "critical", title: "Apparel Packaging Tear Reports", desc: "Multiple torn-package complaints.", category: "Apparel", region: "Rajasthan", batch: "Batch #C044", change: "Packaging: 78% → 59% (↓19 pts)", time: "2 days ago", resolved: false },
  { id: 8, severity: "resolved", title: "FMCG Delivery Recovery", desc: "Logistics partner switched.", category: "FMCG", region: "Maharashtra", batch: "All", change: "Delivery: 65% → 79% (+14 pts)", time: "3 days ago", resolved: true },
];

export const ANOMALY_TIMELINE = Array.from({ length: 12 }, (_, i) => ({
  week: `W${i + 1}`,
  count: [2, 3, 1, 4, 5, 2, 3, 7, 4, 3, 5, 2][i],
  critical: [0, 1, 0, 1, 2, 0, 1, 3, 1, 1, 2, 0][i],
}));

export const PERSONA_PRODUCTS: Record<string, Array<{ name: string; category: string; score: number; price: string; highlights: string[]; store: "Amazon" | "Flipkart" }>> = {
  Student: [
    { name: "Boat Airdopes 141", category: "Electronics", score: 91, price: "₹1,099 – ₹1,499", highlights: ["Battery 89%", "Value 92%", "Durability 86%"], store: "Amazon" },
    { name: "Realme Narzo 60", score: 78, category: "Electronics", price: "₹13,999 – ₹16,999", highlights: ["Display 84%", "Value 88%", "Battery 80%"], store: "Flipkart" },
    { name: "Lenovo Ideapad Slim 3", score: 82, category: "Electronics", price: "₹39,990 – ₹44,990", highlights: ["Performance 85%", "Battery 82%", "Build 78%"], store: "Amazon" },
    { name: "Wildcraft Backpack", score: 86, category: "Apparel", price: "₹1,499 – ₹2,299", highlights: ["Durability 90%", "Comfort 84%", "Value 88%"], store: "Flipkart" },
    { name: "Nescafé Sunrise", score: 80, category: "FMCG", price: "₹120 – ₹350", highlights: ["Taste 82%", "Value 88%", "Quality 78%"], score_alt: 80 } as any,
    { name: "Maggi 2-Min Noodles", score: 84, category: "FMCG", price: "₹14 – ₹140", highlights: ["Taste 88%", "Value 92%", "Availability 95%"], store: "Amazon" },
    { name: "Kotex Travel Mug", score: 79, category: "Apparel", price: "₹399 – ₹599", highlights: ["Insulation 82%", "Build 80%", "Value 84%"], store: "Flipkart" },
    { name: "Mi Smart Band 7", score: 83, category: "Electronics", price: "₹2,499 – ₹3,299", highlights: ["Battery 88%", "Display 80%", "Fit 84%"], store: "Amazon" },
    { name: "Adidas Track Pant", score: 80, category: "Apparel", price: "₹1,299 – ₹1,899", highlights: ["Comfort 84%", "Fit 82%", "Durability 78%"], store: "Flipkart" },
    { name: "Logitech M171 Mouse", score: 88, category: "Electronics", price: "₹599 – ₹799", highlights: ["Reliability 92%", "Comfort 86%", "Value 90%"], store: "Amazon" },
    { name: "Faber-Castell Stationery", score: 86, category: "FMCG", price: "₹250 – ₹650", highlights: ["Quality 90%", "Value 86%", "Variety 84%"], store: "Flipkart" },
    { name: "Boat Stone 190", score: 82, category: "Electronics", price: "₹999 – ₹1,499", highlights: ["Sound 84%", "Battery 84%", "Build 80%"], store: "Amazon" },
  ],
  Family: [
    { name: "Amul Pure Ghee 1L", score: 94, category: "FMCG", price: "₹599 – ₹699", highlights: ["Quality 96%", "Taste 94%", "Trust 95%"], store: "Flipkart" },
    { name: "Tata Sampann Dal", score: 88, category: "FMCG", price: "₹120 – ₹180", highlights: ["Quality 90%", "Taste 88%", "Value 88%"], store: "Amazon" },
    { name: "Samsung 253L Fridge", score: 85, category: "Electronics", price: "₹24,990 – ₹28,490", highlights: ["Cooling 88%", "Energy 84%", "Build 84%"], store: "Flipkart" },
    { name: "Prestige 3L Cooker", score: 87, category: "FMCG", price: "₹1,899 – ₹2,499", highlights: ["Quality 90%", "Safety 88%", "Durability 86%"], store: "Amazon" },
    { name: "FabIndia Kurta Set", score: 82, category: "Apparel", price: "₹1,499 – ₹2,499", highlights: ["Fabric 86%", "Fit 80%", "Value 80%"], store: "Flipkart" },
    { name: "Saffola Active Oil", score: 81, category: "FMCG", price: "₹220 – ₹290", highlights: ["Quality 84%", "Health 84%", "Value 78%"], store: "Amazon" },
    { name: "Wakefit Mattress", score: 89, category: "Apparel", price: "₹8,999 – ₹14,999", highlights: ["Comfort 92%", "Durability 88%", "Value 88%"], store: "Flipkart" },
    { name: "Britannia Choco Roll", score: 78, category: "FMCG", price: "₹40 – ₹120", highlights: ["Taste 82%", "Value 78%", "Packaging 74%"], store: "Amazon" },
    { name: "Philips Mixer Grinder", score: 84, category: "Electronics", price: "₹3,490 – ₹4,490", highlights: ["Power 86%", "Build 84%", "Warranty 84%"], store: "Flipkart" },
    { name: "Manyavar Sherwani", score: 84, category: "Apparel", price: "₹6,999 – ₹14,999", highlights: ["Fabric 88%", "Fit 82%", "Finish 84%"], store: "Amazon" },
    { name: "Haldiram's Snack Pack", score: 80, category: "FMCG", price: "₹40 – ₹250", highlights: ["Taste 84%", "Value 80%", "Variety 76%"], store: "Flipkart" },
    { name: "MTR Ready Mix", score: 85, category: "FMCG", price: "₹60 – ₹140", highlights: ["Taste 88%", "Convenience 88%", "Quality 80%"], store: "Amazon" },
  ],
  Professional: [
    { name: "Allen Solly Formal Shirt", score: 86, category: "Apparel", price: "₹1,499 – ₹2,499", highlights: ["Fabric 88%", "Fit 86%", "Wash care 84%"], store: "Amazon" },
    { name: "Apple iPhone 15", score: 88, category: "Electronics", price: "₹69,990 – ₹79,990", highlights: ["Camera 90%", "Build 92%", "Battery 84%"], store: "Flipkart" },
    { name: "Lenovo ThinkPad E14", score: 85, category: "Electronics", price: "₹62,000 – ₹74,990", highlights: ["Reliability 88%", "Keyboard 90%", "Battery 80%"], store: "Amazon" },
    { name: "Bose QC45 Headphones", score: 90, category: "Electronics", price: "₹26,900 – ₹32,900", highlights: ["ANC 94%", "Comfort 90%", "Sound 92%"], store: "Flipkart" },
    { name: "Van Heusen Trousers", score: 84, category: "Apparel", price: "₹1,799 – ₹2,599", highlights: ["Fabric 86%", "Fit 84%", "Finish 82%"], store: "Amazon" },
    { name: "Hidesign Briefcase", score: 87, category: "Apparel", price: "₹4,999 – ₹8,999", highlights: ["Build 90%", "Look 88%", "Durability 86%"], store: "Flipkart" },
    { name: "Logitech MX Master 3S", score: 92, category: "Electronics", price: "₹8,495 – ₹9,995", highlights: ["Ergonomics 94%", "Battery 90%", "Build 92%"], store: "Amazon" },
    { name: "Nespresso Inissia", score: 84, category: "Electronics", price: "₹9,500 – ₹11,990", highlights: ["Coffee 88%", "Speed 86%", "Build 80%"], store: "Flipkart" },
    { name: "Steelcase Series 1 Chair", score: 89, category: "Apparel", price: "₹39,990 – ₹49,990", highlights: ["Comfort 92%", "Support 90%", "Build 88%"], store: "Amazon" },
    { name: "Samsonite Carry-On", score: 86, category: "Apparel", price: "₹6,999 – ₹10,999", highlights: ["Wheels 88%", "Build 86%", "Capacity 84%"], store: "Flipkart" },
    { name: "Park Avenue Blazer", score: 80, category: "Apparel", price: "₹3,499 – ₹5,499", highlights: ["Cut 82%", "Fabric 80%", "Finish 78%"], store: "Amazon" },
    { name: "Boat Airdopes Pro Plus", score: 82, category: "Electronics", price: "₹1,799 – ₹2,499", highlights: ["Calls 84%", "ANC 80%", "Battery 84%"], store: "Flipkart" },
  ],
  "Heavy User": [
    { name: "Asus ROG Phone 7", score: 89, category: "Electronics", price: "₹64,999 – ₹74,999", highlights: ["Performance 94%", "Battery 88%", "Cooling 86%"], store: "Amazon" },
    { name: "JBL PartyBox 110", score: 88, category: "Electronics", price: "₹26,999 – ₹32,999", highlights: ["Sound 92%", "Battery 86%", "Build 86%"], store: "Flipkart" },
    { name: "OnePlus 12", score: 87, category: "Electronics", price: "₹64,999 – ₹74,999", highlights: ["Speed 92%", "Charging 94%", "Display 88%"], store: "Amazon" },
    { name: "Boult Airbass FXR", score: 80, category: "Electronics", price: "₹1,499 – ₹1,999", highlights: ["Battery 88%", "Sound 78%", "Value 84%"], store: "Flipkart" },
    { name: "Adidas Performance Tee", score: 82, category: "Apparel", price: "₹1,299 – ₹1,999", highlights: ["Sweat 86%", "Fit 84%", "Durability 76%"], store: "Amazon" },
    { name: "Decathlon Trekking Shoes", score: 85, category: "Apparel", price: "₹2,999 – ₹4,499", highlights: ["Grip 88%", "Comfort 86%", "Durability 82%"], store: "Flipkart" },
    { name: "Garmin Forerunner 55", score: 87, category: "Electronics", price: "₹17,990 – ₹19,990", highlights: ["GPS 92%", "Battery 88%", "Accuracy 86%"], store: "Amazon" },
    { name: "Optimum Whey 2Kg", score: 89, category: "FMCG", price: "₹4,999 – ₹6,499", highlights: ["Quality 92%", "Mixability 88%", "Taste 86%"], store: "Flipkart" },
    { name: "Boat Stone 1500", score: 84, category: "Electronics", price: "₹4,999 – ₹6,999", highlights: ["Sound 86%", "Battery 84%", "Bass 86%"], store: "Amazon" },
    { name: "Nike Pegasus 40", score: 90, category: "Apparel", price: "₹9,495 – ₹11,995", highlights: ["Cushion 92%", "Mileage 90%", "Fit 88%"], store: "Flipkart" },
    { name: "Mi Power Bank 20000", score: 86, category: "Electronics", price: "₹1,799 – ₹2,499", highlights: ["Capacity 92%", "Speed 86%", "Build 80%"], store: "Amazon" },
    { name: "Wildcraft Hiking Pant", score: 81, category: "Apparel", price: "₹1,799 – ₹2,499", highlights: ["Stretch 84%", "Pockets 86%", "Durability 76%"], store: "Flipkart" },
  ],
};

// Sentiment Trends — multi-line over 12 weeks per category, top 4 brands each
const trendCurve = (start: number, end: number, vol: number, n = 12) =>
  Array.from({ length: n }, (_, i) => Math.round(start + ((end - start) * i) / (n - 1) + Math.sin(i + start) * vol));

export const TRENDS_BRANDS: Record<string, Array<{ name: string; data: number[]; start: number; end: number; best: string; worst: string; status: "Improving!" | "Watch out" | "Stable" }>> = {
  Electronics: [
    { name: "Apple", data: trendCurve(80, 88, 1.5), start: 80, end: 88, best: "Camera", worst: "Price", status: "Improving!" },
    { name: "Samsung", data: trendCurve(72, 76, 2), start: 72, end: 76, best: "Display", worst: "Bloatware", status: "Stable" },
    { name: "boAt", data: trendCurve(60, 88, 2.2), start: 60, end: 88, best: "Delivery", worst: "Build", status: "Improving!" },
    { name: "realme", data: trendCurve(78, 68, 2), start: 78, end: 68, best: "Value", worst: "Support", status: "Watch out" },
  ],
  FMCG: [
    { name: "Amul", data: trendCurve(88, 94, 1.4), start: 88, end: 94, best: "Quality", worst: "Pkg variety", status: "Improving!" },
    { name: "Tata Sampann", data: trendCurve(80, 88, 1.6), start: 80, end: 88, best: "Quality", worst: "Price", status: "Improving!" },
    { name: "MTR Foods", data: trendCurve(78, 85, 1.8), start: 78, end: 85, best: "Taste", worst: "Packaging", status: "Improving!" },
    { name: "ITC", data: trendCurve(82, 80, 1.5), start: 82, end: 80, best: "Distribution", worst: "Innovation", status: "Stable" },
  ],
  Apparel: [
    { name: "Fabindia", data: trendCurve(76, 82, 1.6), start: 76, end: 82, best: "Fabric", worst: "Sizing", status: "Improving!" },
    { name: "Myntra Originals", data: trendCurve(70, 78, 2.1), start: 70, end: 78, best: "Value", worst: "Returns", status: "Improving!" },
    { name: "Biba", data: trendCurve(74, 75, 1.5), start: 74, end: 75, best: "Style", worst: "Durability", status: "Stable" },
    { name: "W", data: trendCurve(78, 71, 1.8), start: 78, end: 71, best: "Style", worst: "Color fade", status: "Watch out" },
  ],
};

export const PRODUCER_TICKER = [
  "⚠ FMCG Batch #A204: Packaging complaints up 18% this week",
  "✅ Electronics: Battery sentiment stable at 82%",
  "🔔 Apparel durability score climbed to 76% — flag for marketing",
  "📉 Tamil Nadu delivery SLA dipping — monitor closely",
];

export const CONSUMER_TICKER = [
  "🔥 iPhone 15 — trending positive in Bengaluru",
  "💡 Best time to buy: festive season deals detected",
  "✨ Boat earphones now 91% positive — students' top pick",
  "🛒 Amul Ghee leads FMCG with 94% quality sentiment",
];
